# Generated by Django 5.0.4 on 2024-04-23 05:53

import django.db.models.deletion
import django_resized.forms
import djrichtextfield.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Band",
            fields=[
                ("band_id", models.AutoField
                 (primary_key=True, serialize=False)),
                ("band_name", models.CharField(max_length=255)),
                (
                    "genre_choices",
                    models.CharField(
                        choices=[
                            ("Rock", "Rock"),
                            ("Pop", "Pop"),
                            ("Hip-Hop", "Hip-Hop"),
                            ("Indie", "Indie"),
                            ("Metal", "Metal"),
                            ("Electronic", "Electronic"),
                            ("RnB", "RnB"),
                            ("Blues", "Blues"),
                            ("Punk", "Punk"),
                            ("Disco", "Disco"),
                        ],
                        default="Rock",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="bands/",
                    ),
                ),
                ("image_alt", models.CharField(max_length=255)),
                ("description", djrichtextfield.models.RichTextField
                 (max_length=5000)),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                ("slug", models.SlugField
                 (blank=True, max_length=255, unique=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["band_name"],
            },
        ),
    ]
