# Generated by Django 5.0.4 on 2024-05-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0002_bandrequest"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BandRequest",
        ),
    ]
