# Generated by Django 5.0.4 on 2024-05-03 20:11

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bands", "0003_delete_bandrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="band",
            name="motivation",
            field=djrichtextfield.models.RichTextField(
                default="Default motivation", max_length=5000
            ),
        ),
    ]
